In [1]:
from bs4 import BeautifulSoup

In [10]:
html='''<a id='a1' class="c1" href="https://google.com">Google</a>
<a id='a2' class="c1"  href="https://yahoo.com">Yahoo</a>
<a id='a3' class="c3" href="https://facebook.com">Facebook</a>
'''
soup = BeautifulSoup(html,"html5lib")
print(soup.find(id="a1").getText())
print(soup.find(id="a1").get("href"))
tmpList = soup.find_all(class_="c1")
for tag in tmpList:
    print(tag.get("href"),tag.getText())

Google
https://google.com
https://google.com Google
https://yahoo.com Yahoo


In [15]:
html='''<a id='a1' class="c1" href="https://google.com">Google</a>
<a id='a2' class="c1"  href="https://yahoo.com">Yahoo</a>
<a id='a3' class="c3" href="https://facebook.com">Facebook</a>
'''
soup = BeautifulSoup(html,"html5lib")
print(soup.find(id="a1").getText())
print(soup.find(id="a1").get("href"))
tmpList = soup.find_all(class_="c1")
for tag in tmpList:
    print(tag.get("href"),tag.getText())

Google
https://google.com
https://google.com Google
https://yahoo.com Yahoo


## BeautifulSoup Base
find() 只找第一個符合條件的

https://www.crummy.com/software/BeautifulSoup/bs4/doc.zh/#find-all

find_all() 找所有符合條件的

select_one() 只找一個符合條件的可直接使用css語法

select() 找所有符合條件的可使用css語法

In [16]:
from bs4 import BeautifulSoup
html='''<a id='a1' class="c1">V1</a>
<a id='a2' class="c1">V2</a>
<a id='a3' class="c3">V3</a>
'''
soup = BeautifulSoup(html,"html5lib")
print(soup.find(id="a1"))
print(soup.find_all(class_ = "c1"))

<a class="c1" id="a1">V1</a>
[<a class="c1" id="a1">V1</a>, <a class="c1" id="a2">V2</a>]


In [30]:
import requests
from bs4 import BeautifulSoup
url = "https://zh.wikipedia.org/zh-tw/2025年电影"
resp = requests.get(url)
resp.encoding = "utf-8"
soup = BeautifulSoup(resp.text,"html5lib")
movieTable = soup.find("table",class_="wikitable sortable")
tbody = movieTable.find("tbody")
trList = tbody.find_all("tr")
for inx in range(1,len(trList)):
    print("排名:",trList[inx].find("th").text,end="")
    print("片名:",trList[inx].select_one("a").text)
    print("全球票房:",trList[inx].find_all("td")[2].text)

排名: 1
片名: 哪吒之魔童鬧海
全球票房: $2,123,757,964[3][4]

排名: 2
片名: 星際寶貝：史迪奇
全球票房: $1,030,499,804

排名: 3
片名: MINECRAFT麥塊電影
全球票房: $955,149,195

排名: 4
片名: 侏羅紀世界：重生
全球票房: $828,832,885

排名: 5
片名: 馴龍高手
全球票房: $626,363,775

排名: 6
片名: 不可能的任務：最終清算
全球票房: $596,513,515

排名: 7
片名: 超人
全球票房: $594,590,135

排名: 8
片名: F1電影
全球票房: $590,548,183

排名: 9
片名: 唐探1900
全球票房: $495,792,456[3]

排名: 10
片名: 驚奇4超人：第一步
全球票房: $469,480,403



## Numpy簡介

In [32]:
import numpy as np
c1 = [1,3,5,7,9]
d1 = [3,5,6,7,9]
f1 = c1 + d1
print(f1)
c2 = np.array(c1)
d2 = np.array(d1)
f2 = c2 + d2
print(f2)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]
[ 4  8 11 14 18]


+ ndarray.ndim
   + 維度的數量。
+ ndarray.shape
   + 顯示出陣列在每個維度上的整數值。
+ ndarray.size
   + 陣列內元素的總數。
+ ndarray.dtype
   + 用來描述陣列中元素類型的對象。

In [42]:
import numpy as np

i = [[1,2,3],
     [1,2,3]]
a = np.array(i,dtype=np.int8)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 3)
6
int8


In [52]:
import numpy as np
a = np.array([6,7,8,9])
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
d = b ** 2
print(d)
f = np.array([5,-1,3,9,0])
print(f <= 3)
print(f[f <= 3])
f[f <= 3] = 1 # 小於等於3的數值都改成1
print(f)

[6 7 8 9]
[0 1 2 3]
[6 6 6 6]
[0 1 4 9]
[False  True  True False  True]
[-1  3  0]
[5 1 1 9 1]


In [58]:
import numpy as np
x = np.ones((2,4))
print(x)
x = np.full((2,4),6)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6 6 6]
 [6 6 6 6]]


In [60]:
x = np.eye(3)
print(x)
x = np.diag([1,2,3,4])
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [66]:
import numpy as np
x = np.linspace(1,10,6)
print(x)
x = np.linspace(1,10,6).reshape((2,3))#(10-1)/(6-1)
print(x)
x = np.arange(8).reshape((2,4))
print(x)

[ 1.   2.8  4.6  6.4  8.2 10. ]
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
[[0 1 2 3]
 [4 5 6 7]]


In [68]:
import numpy as np
r1 = np.arange(25,30,0.5)
print(r1)

[25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [69]:
lin = np.linspace(3,5,9)# 5-3/ 9-1
print(lin)

[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


## 陣列指定位置取值
+ 間隔選取 [::c]
  + 以 1 維陣列來說明 x[a:b:c]
  + a：選取資料的起始索引
  + b：選取資料的結束索引 +1
  + c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示 1
+ 倒序 [::-1]
  + 只是單純的把順序反過來

## 陣列指定位置-給予一個整數
+ 關於指定位置  [row,column]
+ 假設給予一個整數為 N
 + 如果是給固定的 N，那就代表 row 或 column 等於 N。
 + 如果是 N：，那就代表 row 或 column 大於等於 N 的區域。
 + 如果是：N，那就代表 row 或 column 小於 N 的區域。 
 + 如果是：，那就代表 row 或 column 是任意欄位。

In [77]:
import numpy as np
a = np.arange(1,7).reshape((2,3))
print(a)
print(a.shape)
print(a[0])
print(a[0][2])

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3]
3


In [82]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[1,2])
print(a[2,:2])
print(a[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[7 8]
[2 5 8]


In [83]:
import numpy as np
a=np.arange(0,36).reshape((6,6))
print(a)
#作業
# [3 4]
"""
[[28 29]
 [34 35]]
"""

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
